insert into books (Title, Author, Genre, Country, yearReleased) values ('Moby-Dick', 'Lily Turner', 'Romance', 'Jamaica', 1876);
insert into books (Title, Author, Genre, Country, yearReleased) values ('To Kill a Mockingbird', 'Abigail Adams', 'Western', 'Switzerland', 1963);
insert into books (Title, Author, Genre, Country, yearReleased) values ('1984', 'Samantha Turner', 'Memoir', 'Japan', 1872);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Stand', 'Samantha Coleman', 'Adventure', 'Rwanda', 1890);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Sun Also Rises', 'Samantha Rogers', 'Thriller', 'Tunisia', 1867);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Moby-Dick', 'Scarlett Murphy', 'Mystery', 'Nigeria', 2009);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Old Man and the Sea', 'Michael Wright', 'Drama', 'Tunisia', 1956);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Bell Jar', 'Emily Johnson', 'Memoir', 'Mali', 1885);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Count of Monte Cristo', 'Abigail Adams', 'Biography', 'Cameroon', 1980);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Stand', 'Matthew Butler', 'Thriller', 'El Salvador', 1908);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Sun Also Rises', 'Olivia Martinez', 'Self-help', 'Sao Tome and Principe', 1942);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Little Prince', 'Henry Cooper', 'Comedy', 'Russia', 2019);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Picture of Dorian Gray', 'Gabriel Cox', 'Satire', 'Equatorial Guinea', 1961);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Moby-Dick', 'Anthony Peterson', 'Western', 'Burkina Faso', 1982);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Picture of Dorian Gray', 'Andrew Bell', 'Science Fiction', 'Bhutan', 1972);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hobbit', 'Michael Wright', 'Fantasy', 'Yemen', 1983);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Scarlet Letter', 'Henry Reed', 'Historical Fiction', 'Marshall Islands', 1970);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Alchemist', 'Ella Adams', 'Crime', 'Jordan', 1876);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Picture of Dorian Gray', 'Lily Foster', 'Science Fiction', 'United Arab Emirates', 1862);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Fault in Our Stars', 'Jackson Foster', 'Drama', 'Croatia', 2004);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Da Vinci Code', 'Andrew Simmons', 'Horror', 'Botswana', 1901);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Grapes of Wrath', 'Chloe Simmons', 'Crime', 'Saint Kitts and Nevis', 1901);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hitchhiker''s Guide to the Galaxy', 'Matthew Butler', 'Comedy', 'Croatia', 1966);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hitchhiker''s Guide to the Galaxy', 'Chloe Coleman', 'Adventure', 'Mongolia', 1922);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Bell Jar', 'Michael Wright', 'Fantasy', 'Uzbekistan', 2019);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Giver', 'Harper Reed', 'Young Adult', 'Croatia', 1969);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Maze Runner', 'Christopher Peterson', 'Crime', 'Saint Kitts and Nevis', 1947);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Moby-Dick', 'Joseph Hernandez', 'Historical Fiction', 'Bangladesh', 1998);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Gone Girl', 'Samuel Murphy', 'Graphic Novel', 'Azerbaijan', 1883);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Help', 'David Walker', 'Horror', 'Jordan', 2006);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Addison Phillips', 'Satire', 'Comoros', 1985);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Old Man and the Sea', 'Samuel Murphy', 'Western', 'United Kingdom', 2019);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Great Gatsby', 'Zoe Cox', 'Comedy', 'Micronesia', 1996);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Grapes of Wrath', 'Ella Ramirez', 'Comedy', 'Bolivia', 1967);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Alchemist', 'Emma Wilson', 'Science Fiction', 'Senegal', 1942);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Alchemist', 'Christopher Peterson', 'Horror', 'Thailand', 1887);
insert into books (Title, Author, Genre, Country, yearReleased) values ('1984', 'Anthony Howard', 'Classic', 'Saudi Arabia', 1955);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Secret Life of Bees', 'Lily Turner', 'Poetry', 'Hungary', 1910);
insert into books (Title, Author, Genre, Country, yearReleased) values ('To Kill a Mockingbird', 'David Anderson', 'Horror', 'Vatican City', 1933);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Old Man and the Sea', 'Christopher Reed', 'Romance', 'Djibouti', 1938);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Lord of the Rings', 'Lily Gray', 'Mystery', 'Saint Kitts and Nevis', 1948);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Pride and Prejudice', 'Anthony Peterson', 'Satire', 'Slovakia', 2019);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Fault in Our Stars', 'Chloe Phillips', 'Romance', 'Bahamas', 1872);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hobbit', 'Chloe Phillips', 'Crime', 'Trinidad and Tobago', 1973);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Scarlet Letter', 'Sophia Taylor', 'Drama', 'Belarus', 1901);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Girl on the Train', 'Isabella Moore', 'Western', 'Canada', 2019);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Stand', 'Henry Cooper', 'Self-help', 'Bolivia', 1972);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Samuel Murphy', 'Western', 'Morocco', 1872);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Giver', 'Anthony Ramirez', 'Poetry', 'Saint Lucia', 1867);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Diary of a Young Girl', 'Avery Howard', 'Graphic Novel', 'Mexico', 1985);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Adventures of Huckleberry Finn', 'Emma Wilson', 'Poetry', 'United Kingdom', 1945);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Lovely Bones', 'Natalie Murphy', 'Adventure', 'Cabo Verde', 2004);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Help', 'Joshua Rogers', 'Historical Fiction', 'Kenya', 1908);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Scarlet Letter', 'Madison Price', 'Science Fiction', 'Comoros', 1933);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Lovely Bones', 'Christopher Foster', 'Adventure', 'Brazil', 1983);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Girl on the Train', 'Avery Howard', 'Science Fiction', 'Australia', 1955);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Samuel Scott', 'Self-help', 'Seychelles', 1970);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hobbit', 'Zoe Howard', 'Drama', 'Bosnia and Herzegovina', 1935);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Grapes of Wrath', 'Lily Turner', 'Western', 'Guatemala', 1970);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Kite Runner', 'Natalie Rivera', 'Young Adult', 'Kuwait', 1966);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Chronicles of Narnia', 'Anthony Ramirez', 'Romance', 'Ethiopia', 1922);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hunger Games', 'Harper Reed', 'Science Fiction', 'Slovakia', 1990);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Color Purple', 'Grace Turner', 'Historical Fiction', 'Armenia', 1885);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Shining', 'Christopher Turner', 'Comedy', 'Ireland', 1892);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Outsiders', 'Lily Turner', 'Fantasy', 'Tanzania', 1920);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Pride and Prejudice', 'Addison Murphy', 'Romance', 'Kazakhstan', 1955);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Little Prince', 'Aria Turner', 'Classic', 'Cabo Verde', 1961);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Grace Turner', 'Graphic Novel', 'Somalia', 1966);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Secret Life of Bees', 'Christopher Mitchell', 'Historical Fiction', 'Lesotho', 1867);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Adventures of Huckleberry Finn', 'Jackson Foster', 'Young Adult', 'Chad', 1977);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Diary of a Young Girl', 'Anthony Ramirez', 'Crime', 'Mali', 1977);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Diary of a Young Girl', 'Aria Powell', 'Comedy', 'Egypt', 1961);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Chronicles of Narnia', 'Madison Cox', 'Adventure', 'Czech Republic', 1864);
insert into books (Title, Author, Genre, Country, yearReleased) values ('To Kill a Mockingbird', 'Joseph Adams', 'Fantasy', 'Marshall Islands', 1953);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Da Vinci Code', 'Gabriel Rivera', 'Historical Fiction', 'Eswatini', 1949);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Count of Monte Cristo', 'Avery Watson', 'Mystery', 'Gambia', 1983);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Giver', 'Emily Johnson', 'Fantasy', 'Mauritania', 1876);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Kite Runner', 'Aria Powell', 'Crime', 'Qatar', 1910);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Bell Jar', 'Samuel Nelson', 'Crime', 'Slovakia', 2002);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Color Purple', 'Olivia Martinez', 'Classic', 'Tanzania', 1862);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Scarlet Letter', 'Amelia Cox', 'Self-help', 'Barbados', 1987);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hobbit', 'Matthew Butler', 'Romance', 'Bahamas', 1983);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hunger Games', 'Avery Mitchell', 'Horror', 'Colombia', 2006);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Adventures of Huckleberry Finn', 'Victoria Reed', 'Graphic Novel', 'Mali', 1940);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hitchhiker''s Guide to the Galaxy', 'Avery Mitchell', 'Crime', 'Portugal', 1901);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Help', 'Matthew Foster', 'Self-help', 'Japan', 1876);
insert into books (Title, Author, Genre, Country, yearReleased) values ('Harry Potter and the Sorcerer''s Stone', 'Addison Coleman', 'Fantasy', 'Marshall Islands', 1985);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Old Man and the Sea', 'Zoe Howard', 'Thriller', 'Pakistan', 1903);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Little Prince', 'David Walker', 'Poetry', 'Denmark', 1969);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Great Gatsby', 'Ella Adams', 'Self-help', 'Yemen', 1883);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Zoe Howard', 'Historical Fiction', 'Eswatini', 1939);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Great Gatsby', 'Daniel Simmons', 'Horror', 'Eswatini', 1951);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Girl on the Train', 'Alexander Young', 'Thriller', 'Cambodia', 1966);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Catcher in the Rye', 'Ella Adams', 'Satire', 'Liberia', 1953);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Chronicles of Narnia', 'Addison Coleman', 'Romance', 'Central African Republic', 1948);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Lovely Bones', 'David Powell', 'Young Adult', 'Argentina', 1869);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Stand', 'Samantha Coleman', 'Crime', 'Switzerland', 1966);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Little Prince', 'Avery Gray', 'Graphic Novel', 'Samoa', 1864);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Hitchhiker''s Guide to the Galaxy', 'Madison Price', 'Self-help', 'Papua New Guinea', 1876);
insert into books (Title, Author, Genre, Country, yearReleased) values ('The Great Gatsby', 'Ella Brooks', 'Historical Fiction', 'Luxembourg', 2002);
